name: CI

on: [push, pull_request]

jobs:
  Linter:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1
          bundler-cache: true

      - name: Run bundle install
        run: |
          gem install bundler -v 2.2.16
          bundle install

      - name: Run rubocop
        run: bundle exec rake rubocop

  Specs:
    name: Specs
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.0']

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run bundle install
        run: |
          gem install bundler -v 2.2.16
          bundle install

      - name: Run specs
        run: bundle exec rake spec
